# -*- coding: utf-8 -*-
"""CLONE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wIL9yfYzNPXP-ZoEO1YKRl2g8Eypa0hY
"""

pip install gitpython

import git

git.Repo.clone_from('https://gitlab.com/inside-edge/python_hiring_test.git', 'python_hiring_test.git')

cd python_hiring_test.git

pip install -r requirements.txt